In [1]:
import tensorflow as tf
import numpy as np

## Save TF logs

**TF_CPP_MIN_LOG_LEVEL' = 3**

0 - default

1 - Info  & warning

3 - to print INFO, WARNING, and ERROR (logs)

In [14]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

## tf.placeholder :

var = tf.placeholder(dtype, shape=None, name=None)

return : A Tensor that may be used as a handle for feeding a value, but not evaluated directly.

Inserts a placeholder for a tensor that will be always fed.

#### Important : This sparse tensor will produce an error if evaluated. Its value must be fed using the 'feed_dict' optional argument to :

#### 1)  Session.run()

#### 2) Tensor.eval()

#### 3) or Operation.run() 


In [35]:
tensor_shape = (1024, 1024)

x = tf.placeholder(tf.float32, shape=tensor_shape)
y = tf.matmul(x, x)

with tf.Session() as sess:
    try:
        print(sess.run(y))  # ERROR: will fail because x was not fed.
    except:
        print("\nCan't execute print(sess.run(y))  # ERROR: will fail because x was not fed.\n")
    
    rand_array = np.random.rand(tensor_shape[0], tensor_shape[1])
    
    # using Session.run()
    print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.
    
    # using tensor.eval()
    print(y.eval(feed_dict={x : rand_array}))
    
    # using operation.run()
    


Can't execute print(sess.run(y))  # ERROR: will fail because x was not fed.

[[256.6363  255.8678  259.14847 ... 258.26315 263.1412  251.64508]
 [258.46945 255.74954 250.7579  ... 255.4925  260.5408  252.66284]
 [246.63448 251.98642 248.14177 ... 247.89966 258.2569  245.19122]
 ...
 [246.70215 244.92694 244.9447  ... 253.20427 250.85568 246.10928]
 [258.28192 257.1183  257.39594 ... 261.55978 263.57156 251.56071]
 [246.87756 239.96147 241.90071 ... 238.54813 244.32901 237.52194]]
[[256.6363  255.8678  259.14847 ... 258.26315 263.1412  251.64508]
 [258.46945 255.74954 250.7579  ... 255.4925  260.5408  252.66284]
 [246.63448 251.98642 248.14177 ... 247.89966 258.2569  245.19122]
 ...
 [246.70215 244.92694 244.9447  ... 253.20427 250.85568 246.10928]
 [258.28192 257.1183  257.39594 ... 261.55978 263.57156 251.56071]
 [246.87756 239.96147 241.90071 ... 238.54813 244.32901 237.52194]]


## tf.sparse_placeholder : 

var = tf.sparse_placeholder(dtype, shape=None, name=None)

return : A SparseTensor that may be used as a handle for feeding a value, but not evaluated directly.

#### Important : This sparse tensor will produce an error if evaluated. Its value must be fed using the 'feed_dict' optional argument to :

#### 1)  Session.run()

#### 2) Tensor.eval()

#### 3) or Operation.run() 

In [64]:
x = tf.sparse_placeholder(tf.float32)
y = tf.sparse_reduce_sum(x)

with tf.Session() as sess:
    try:
        print(sess.run(y))  # ERROR: will fail because x was not fed.
    except:
        print("\nCan't execute print(sess.run(y))  # ERROR: will fail because x was not fed.\n")
        
    indices = np.array([[3, 2, 0], [4, 5, 1]], dtype=np.int64)
    print(f"indices shape : {indices.shape}")
    values = np.array([1.0, 2.0], dtype=np.float32)
    print(f"values shape : {values.shape}")
    shape = np.array([7, 9, 2], dtype=np.int64)
    print(f"shape's shape : {shape.shape}\n")
    
    # Session.run ()
    print(sess.run(y, feed_dict={
        x: tf.SparseTensorValue(indices, values, shape)}))  # Will succeed.
    
    print(sess.run(y, feed_dict={
        x: (indices, values, shape)}))  # Will succeed.
    
    # tensor.eval ()
    sp = tf.SparseTensor(indices=indices, values=values, dense_shape=shape)
    sp_value = sp.eval(session=sess)
    
    # operation.run()
    print(sess.run(y, feed_dict={x: sp_value}))  # Will succeed.


Can't execute print(sess.run(y))  # ERROR: will fail because x was not fed.

indices shape : (2, 3)
values shape : (2,)
shape's shape : (3,)

3.0
3.0
3.0


## tf.placeholder_with_default

tf.placeholder_with_default(input,shape,name=None)

- input: A Tensor. The default value to produce when output is not fed.

- shape: A tf.TensorShape or list of ints. The (possibly partial) shape of the tensor.

- name: A name for the operation (optional).

Returns:
A Tensor. Has the same type as input.

## tf.fill

tf.fill(dims, value, name=None)

- dims: A Tensor. Must be one of the following types: int32, int64. 1-D. Represents the shape of the output tensor.
- value: A Tensor. 0-D (scalar). Value to fill the returned tensor.
- name: A name for the operation (optional).


Output tensor has shape [2, 3].

- fill([2, 3], 9) ==> 

                     [[9, 9, 9]

                     [9, 9, 9]]

In [75]:
with tf.Session() as sess:
    
    x = tf.placeholder(tf.float32, shape=(2,10))
    
    width = 10
    
#     print(tf.shape(x).eval())
    
    var = tf.fill(tf.shape(x), width, name="y_len")
    
    print(var.eval())

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]]


## tf.contrib.layers.xavier_initializer

tf.contrib.layers.xavier_initializer(uniform=True, seed=None, dtype=tf.float32)

- uniform: Whether to use uniform or normal distributed random initialization.
- seed: A Python integer. Used to create random seeds. See tf.set_random_seed for behavior.
- dtype: The data type. Only floating point types are supported.


Returns : An initializer for a weight matrix.


This initializer is designed to keep the scale of the gradients roughly the same in all layers.

In uniform distribution this ends up being the range: x = sqrt(6. / (in + out)); [-x, x] and for normal distribution a standard deviation of sqrt(2. / (in + out)) is used.

In [2]:
weight_initializer = tf.contrib.layers.xavier_initializer()


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

